import { SlotSeedItem } from '../types/slot.types';

export const SLOTS_DATA: SlotSeedItem[] = [
  // RAW
  { wrestlerName: 'AJ Lee', members: [], price: 9, brand: 'RAW' },
  { wrestlerName: 'AJ Styles', members: [], price: 4, brand: 'RAW' },
  { wrestlerName: 'Alexa Bliss', members: [], price: 12, brand: 'RAW' },
  { wrestlerName: 'Asuka & Kairi Sane', members: ['Asuka', 'Kairi Sane'], price: 8, brand: 'RAW' },
  { wrestlerName: 'Becky Lynch', members: [], price: 10, brand: 'RAW' },
  { wrestlerName: 'Bianca Belair w/Street Profits', members: ['Bianca Belair', 'Angelo Dawkins', 'Montez Ford'], price: 7, brand: 'RAW' },
  { wrestlerName: 'Bray Wyatt', members: [], price: 6, brand: 'RAW' },
  { wrestlerName: 'Carmelo Hayes', members: [], price: 5, brand: 'RAW' },
  { wrestlerName: 'Damian Priest & Ron Killings', members: ['Damian Priest', 'Ron Killings'], price: 4, brand: 'RAW' },
  { wrestlerName: 'Dominik Mysterio', members: [], price: 3, brand: 'RAW' },
  { wrestlerName: 'Drew McIntyre', members: [], price: 6, brand: 'RAW' },
  { wrestlerName: 'Fatal Influence', members: [], price: 5, brand: 'RAW' },
  { wrestlerName: 'Finn Bálor', members: [], price: 7, brand: 'RAW' },
  { wrestlerName: 'Ilja Dragunov & Tyler Bates & Pete Dunne', members: ['Ilja Dragunov', 'Tyler Bates', 'Pete Dunne'], price: 5, brand: 'RAW' },
  { wrestlerName: 'Judgement Day', members: [], price: 8, brand: 'RAW' },
  { wrestlerName: 'Kevin Owens', members: [], price: 7, brand: 'RAW' },
  { wrestlerName: 'LA Knight', members: [], price: 8, brand: 'RAW' },
  { wrestlerName: 'Liv Morgan & Racquel Rodriguez', members: ['Liv Morgan', 'Racquel Rodriguez'], price: 6, brand: 'RAW' },
  { wrestlerName: 'Ludwig Kaiser', members: [], price: 3, brand: 'RAW' },
  { wrestlerName: 'Lyra Valkyria', members: [], price: 5, brand: 'RAW' },
  { wrestlerName: 'Naomi', members: [], price: 4, brand: 'RAW' },
  { wrestlerName: 'Nia Jax & Lash Legend & Candice LeRae', members: ['Nia Jax', 'Lash Legend', 'Candice LeRae'], price: 5, brand: 'RAW' },
  { wrestlerName: 'Penta', members: [], price: 6, brand: 'RAW' },
  { wrestlerName: 'Randy Orton & Batista', members: ['Randy Orton', 'Batista'], price: 9, brand: 'RAW' },
  { wrestlerName: 'Rey Fenix', members: [], price: 5, brand: 'RAW' },
  { wrestlerName: 'Rhea Ripley', members: [], price: 12, brand: 'RAW' },
  { wrestlerName: 'Sami Zayn', members: [], price: 7, brand: 'RAW' },
  { wrestlerName: 'Seth Rollins', members: [], price: 11, brand: 'RAW' },
  { wrestlerName: 'Sheamus', members: [], price: 4, brand: 'RAW' },
  // SMACKDOWN
  { wrestlerName: 'Aleister Black & Zelina Vega', members: ['Aleister Black', 'Zelina Vega'], price: 3, brand: 'SMACKDOWN' },
  { wrestlerName: 'Bayley', members: [], price: 9, brand: 'SMACKDOWN' },
  { wrestlerName: 'Charlotte Flair', members: [], price: 11, brand: 'SMACKDOWN' },
  { wrestlerName: 'Chelsea Green & Alba Fyre', members: ['Chelsea Green', 'Alba Fyre'], price: 4, brand: 'SMACKDOWN' },
  { wrestlerName: 'CM Punk', members: [], price: 13, brand: 'SMACKDOWN' },
  { wrestlerName: 'Ethan Page', members: [], price: 3, brand: 'SMACKDOWN' },
  { wrestlerName: 'Giulia', members: [], price: 7, brand: 'SMACKDOWN' },
  { wrestlerName: 'Gunther', members: [], price: 12, brand: 'SMACKDOWN' },
  { wrestlerName: 'Iyo Sky', members: [], price: 8, brand: 'SMACKDOWN' },
  { wrestlerName: 'Jacob Fatu', members: [], price: 8, brand: 'SMACKDOWN' },
  { wrestlerName: 'Jade Cargill & B-Fab & Michin', members: ['Jade Cargill', 'B-Fab', 'Michin'], price: 6, brand: 'SMACKDOWN' },
  { wrestlerName: 'Joe Hendry', members: [], price: 5, brand: 'SMACKDOWN' },
  { wrestlerName: 'Jordynne Grace', members: [], price: 5, brand: 'SMACKDOWN' },
  { wrestlerName: 'Karmen Petrovic', members: [], price: 3, brand: 'SMACKDOWN' },
  { wrestlerName: 'Kelani Jordan', members: [], price: 4, brand: 'SMACKDOWN' },
  { wrestlerName: 'Kiana James', members: [], price: 3, brand: 'SMACKDOWN' },
  { wrestlerName: 'Lola Vice', members: [], price: 4, brand: 'SMACKDOWN' },
  { wrestlerName: 'LWO', members: [], price: 4, brand: 'SMACKDOWN' },
  { wrestlerName: 'MCMG', members: [], price: 5, brand: 'SMACKDOWN' },
  { wrestlerName: 'MFT', members: [], price: 3, brand: 'SMACKDOWN' },
  { wrestlerName: 'Oba Femi', members: [], price: 6, brand: 'SMACKDOWN' },
  { wrestlerName: 'OTM', members: [], price: 4, brand: 'SMACKDOWN' },
  { wrestlerName: 'Piper Niven', members: [], price: 3, brand: 'SMACKDOWN' },
  { wrestlerName: 'Pretty Deadly', members: [], price: 4, brand: 'SMACKDOWN' },
  { wrestlerName: 'Ricky Saints', members: [], price: 3, brand: 'SMACKDOWN' },
  { wrestlerName: 'Roman Reigns', members: [], price: 15, brand: 'SMACKDOWN' },
  { wrestlerName: 'Rusev', members: [], price: 4, brand: 'SMACKDOWN' },
  { wrestlerName: 'Shinsuke Nakamura', members: [], price: 5, brand: 'SMACKDOWN' },
  { wrestlerName: 'Sol Ruca', members: [], price: 4, brand: 'SMACKDOWN' },
  { wrestlerName: 'Stephanie Vaquer', members: [], price: 6, brand: 'SMACKDOWN' },
  { wrestlerName: 'Tatum Paxley', members: [], price: 4, brand: 'SMACKDOWN' },
  { wrestlerName: 'The American Nightmare Cody Rhodes', members: [], price: 14, brand: 'SMACKDOWN' },
  { wrestlerName: 'The Family', members: ['Roman Reigns', 'Solo Sikoa', 'Sami Zayn'], price: 12, brand: 'SMACKDOWN' },
  { wrestlerName: 'The Rock', members: [], price: 15, brand: 'SMACKDOWN' },
  { wrestlerName: 'The Vision', members: [], price: 5, brand: 'SMACKDOWN' },
  { wrestlerName: 'Thea Hail', members: [], price: 3, brand: 'SMACKDOWN' },
  { wrestlerName: 'Tiffany Stratton', members: [], price: 9, brand: 'SMACKDOWN' },
  { wrestlerName: 'Wyatt Sicks', members: [], price: 6, brand: 'SMACKDOWN' },
  // NXT
  { wrestlerName: 'American Alpha (Chad Gable, Brutus Creed, Julius Creed, Ivey Nile)', members: ['Chad Gable', 'Brutus Creed', 'Julius Creed', 'Ivey Nile'], price: 3, brand: 'NXT' },
  { wrestlerName: 'American Alpha (Maxxine Dupri, Akira Tozawa, Otis)', members: ['Maxxine Dupri', 'Akira Tozawa', 'Otis'], price: 3, brand: 'NXT' },
  { wrestlerName: 'BirthRight Stable', members: [], price: 4, brand: 'NXT' },
  { wrestlerName: 'Blake Monroe', members: [], price: 3, brand: 'NXT' },
  { wrestlerName: 'Brinley Reece & Carlee Bright', members: ['Brinley Reece', 'Carlee Bright'], price: 3, brand: 'NXT' },
  { wrestlerName: 'Dark Stable', members: [], price: 4, brand: 'NXT' },
  { wrestlerName: 'DIY', members: [], price: 5, brand: 'NXT' },
  { wrestlerName: 'Fraxiom', members: [], price: 5, brand: 'NXT' },
  { wrestlerName: 'Izzi Dame', members: [], price: 3, brand: 'NXT' },
  { wrestlerName: "Je'Von Evans", members: [], price: 4, brand: 'NXT' },
  { wrestlerName: 'Lilian Garcia', members: [], price: 3, brand: 'NXT' },
  { wrestlerName: 'NXT (19 wrestlers)', members: [], price: 6, brand: 'NXT' },
  { wrestlerName: 'Nikkita Lyons', members: [], price: 3, brand: 'NXT' },
  { wrestlerName: 'Trick Williams', members: [], price: 7, brand: 'NXT' },
  { wrestlerName: 'War Raiders', members: [], price: 4, brand: 'NXT' },
  { wrestlerName: 'Wendy Choo', members: [], price: 3, brand: 'NXT' },
  { wrestlerName: 'Wren Sinclair', members: [], price: 3, brand: 'NXT' },
  { wrestlerName: 'Zaria', members: [], price: 3, brand: 'NXT' },
  { wrestlerName: 'Zoey Stark', members: [], price: 4, brand: 'NXT' },
  // LEGENDS
  { wrestlerName: 'Bret Hart & Natalya', members: ['Bret Hart', 'Natalya'], price: 7, brand: 'LEGENDS' },
  { wrestlerName: 'Brock Lesnar', members: [], price: 11, brand: 'LEGENDS' },
  { wrestlerName: 'DX', members: [], price: 10, brand: 'LEGENDS' },
  { wrestlerName: 'ECW', members: [], price: 6, brand: 'LEGENDS' },
  { wrestlerName: 'Hillbilly Jim', members: [], price: 2, brand: 'LEGENDS' },
  { wrestlerName: 'Hulk Hogan', members: [], price: 13, brand: 'LEGENDS' },
  { wrestlerName: 'John Cena', members: [], price: 15, brand: 'LEGENDS' },
  { wrestlerName: 'Jey Uso & Jimmy Uso & Rikishi', members: ['Jey Uso', 'Jimmy Uso', 'Rikishi'], price: 7, brand: 'LEGENDS' },
  { wrestlerName: 'Kane', members: [], price: 9, brand: 'LEGENDS' },
  { wrestlerName: 'Kurt Angle & JBL', members: ['Kurt Angle', 'JBL'], price: 6, brand: 'LEGENDS' },
  { wrestlerName: 'LGDF', members: [], price: 5, brand: 'LEGENDS' },
  { wrestlerName: 'Legends', members: [], price: 8, brand: 'LEGENDS' },
  { wrestlerName: 'Lita & Victoria', members: ['Lita', 'Victoria'], price: 7, brand: 'LEGENDS' },
  { wrestlerName: 'Mark Henry', members: [], price: 5, brand: 'LEGENDS' },
  { wrestlerName: 'Mick Foley', members: [], price: 8, brand: 'LEGENDS' },
  { wrestlerName: 'New Day', members: [], price: 6, brand: 'LEGENDS' },
  { wrestlerName: 'Nikki Bella', members: [], price: 6, brand: 'LEGENDS' },
  { wrestlerName: 'Shawn Michaels', members: [], price: 11, brand: 'LEGENDS' },
  { wrestlerName: 'Stacy Keibler', members: [], price: 7, brand: 'LEGENDS' },
  { wrestlerName: 'Stone Cold Steve Austin', members: [], price: 14, brand: 'LEGENDS' },
  { wrestlerName: 'The Miz & Maryse', members: ['The Miz', 'Maryse'], price: 5, brand: 'LEGENDS' },
  { wrestlerName: 'Torrie Wilson', members: [], price: 6, brand: 'LEGENDS' },
  { wrestlerName: 'Triple H', members: [], price: 12, brand: 'LEGENDS' },
  { wrestlerName: 'Trish Stratus', members: [], price: 10, brand: 'LEGENDS' },
  { wrestlerName: 'Undertaker', members: [], price: 14, brand: 'LEGENDS' },
  { wrestlerName: 'WCW', members: [], price: 5, brand: 'LEGENDS' },
];
